package com.arriendo.modelos;
// Generated 20-11-2017 14:02:58 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Accesorio generated by hbm2java
 */
public class Accesorio  implements java.io.Serializable {


     private int idAccesorio;
     private String descripcion;
     private int precio;
     private Date fechaRegistro;
     private Byte estadoSincr;
     private Set reservaAccesorioses = new HashSet(0);

    public Accesorio() {
    }

	
    public Accesorio(int idAccesorio, String descripcion, int precio) {
        this.idAccesorio = idAccesorio;
        this.descripcion = descripcion;
        this.precio = precio;
    }
    public Accesorio(int idAccesorio, String descripcion, int precio, Date fechaRegistro, Byte estadoSincr, Set reservaAccesorioses) {
       this.idAccesorio = idAccesorio;
       this.descripcion = descripcion;
       this.precio = precio;
       this.fechaRegistro = fechaRegistro;
       this.estadoSincr = estadoSincr;
       this.reservaAccesorioses = reservaAccesorioses;
    }
   
    public int getIdAccesorio() {
        return this.idAccesorio;
    }
    
    public void setIdAccesorio(int idAccesorio) {
        this.idAccesorio = idAccesorio;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public int getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(int precio) {
        this.precio = precio;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Byte getEstadoSincr() {
        return this.estadoSincr;
    }
    
    public void setEstadoSincr(Byte estadoSincr) {
        this.estadoSincr = estadoSincr;
    }
    public Set getReservaAccesorioses() {
        return this.reservaAccesorioses;
    }
    
    public void setReservaAccesorioses(Set reservaAccesorioses) {
        this.reservaAccesorioses = reservaAccesorioses;
    }




}


