package com.arriendo.modelos;
// Generated 18-11-2017 19:47:29 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Accesorio generated by hbm2java
 */
public class Accesorio  implements java.io.Serializable {


     private int idAccesorio;
     private String descripcion;
     private int precio;
     private Date fechaRegistro;
     private Byte estadoSincr;

    public Accesorio() {
    }

	
    public Accesorio(int idAccesorio, String descripcion, int precio) {
        this.idAccesorio = idAccesorio;
        this.descripcion = descripcion;
        this.precio = precio;
    }
    public Accesorio(int idAccesorio, String descripcion, int precio, Date fechaRegistro, Byte estadoSincr) {
       this.idAccesorio = idAccesorio;
       this.descripcion = descripcion;
       this.precio = precio;
       this.fechaRegistro = fechaRegistro;
       this.estadoSincr = estadoSincr;
    }
   
    public int getIdAccesorio() {
        return this.idAccesorio;
    }
    
    public void setIdAccesorio(int idAccesorio) {
        this.idAccesorio = idAccesorio;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public int getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(int precio) {
        this.precio = precio;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Byte getEstadoSincr() {
        return this.estadoSincr;
    }
    
    public void setEstadoSincr(Byte estadoSincr) {
        this.estadoSincr = estadoSincr;
    }




}


