package com.arriendo.modelos;
// Generated 20-11-2017 14:02:58 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Arriendo generated by hbm2java
 */
public class Arriendo  implements java.io.Serializable {


     private int idArriendo;
     private String reservacol;
     private String firmaCliente;
     private String firmaOperador;
     private Date fechaFirmaCliente;
     private Date fechaFirmaOperador;
     private String nombreContrato;
     private Date fechaRegistro;
     private Byte estadoSincr;
     private Set reservas = new HashSet(0);

    public Arriendo() {
    }

	
    public Arriendo(int idArriendo) {
        this.idArriendo = idArriendo;
    }
    public Arriendo(int idArriendo, String reservacol, String firmaCliente, String firmaOperador, Date fechaFirmaCliente, Date fechaFirmaOperador, String nombreContrato, Date fechaRegistro, Byte estadoSincr, Set reservas) {
       this.idArriendo = idArriendo;
       this.reservacol = reservacol;
       this.firmaCliente = firmaCliente;
       this.firmaOperador = firmaOperador;
       this.fechaFirmaCliente = fechaFirmaCliente;
       this.fechaFirmaOperador = fechaFirmaOperador;
       this.nombreContrato = nombreContrato;
       this.fechaRegistro = fechaRegistro;
       this.estadoSincr = estadoSincr;
       this.reservas = reservas;
    }
   
    public int getIdArriendo() {
        return this.idArriendo;
    }
    
    public void setIdArriendo(int idArriendo) {
        this.idArriendo = idArriendo;
    }
    public String getReservacol() {
        return this.reservacol;
    }
    
    public void setReservacol(String reservacol) {
        this.reservacol = reservacol;
    }
    public String getFirmaCliente() {
        return this.firmaCliente;
    }
    
    public void setFirmaCliente(String firmaCliente) {
        this.firmaCliente = firmaCliente;
    }
    public String getFirmaOperador() {
        return this.firmaOperador;
    }
    
    public void setFirmaOperador(String firmaOperador) {
        this.firmaOperador = firmaOperador;
    }
    public Date getFechaFirmaCliente() {
        return this.fechaFirmaCliente;
    }
    
    public void setFechaFirmaCliente(Date fechaFirmaCliente) {
        this.fechaFirmaCliente = fechaFirmaCliente;
    }
    public Date getFechaFirmaOperador() {
        return this.fechaFirmaOperador;
    }
    
    public void setFechaFirmaOperador(Date fechaFirmaOperador) {
        this.fechaFirmaOperador = fechaFirmaOperador;
    }
    public String getNombreContrato() {
        return this.nombreContrato;
    }
    
    public void setNombreContrato(String nombreContrato) {
        this.nombreContrato = nombreContrato;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Byte getEstadoSincr() {
        return this.estadoSincr;
    }
    
    public void setEstadoSincr(Byte estadoSincr) {
        this.estadoSincr = estadoSincr;
    }
    public Set getReservas() {
        return this.reservas;
    }
    
    public void setReservas(Set reservas) {
        this.reservas = reservas;
    }




}


