package com.arriendo.modelos;
// Generated 20-11-2017 14:02:58 by Hibernate Tools 4.3.1


import com.arriendo.utilidades.Utilidades;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Bicicleta generated by hbm2java
 */
public class Bicicleta  implements java.io.Serializable {


     private int idBicicleta;
     private EstadoBicicleta estadoBicicleta;
     private Marca marca;
     private TipoBicicleta tipoBicicleta;
     private String modelo;
     private Integer precio;
     private Date fechaRegistro;
     private Byte estadoSincr;
     private Set reservaBicicletas = new HashSet(0);
     private Set mantencioneses = new HashSet(0);
     private boolean selectedAux = false;

    public Bicicleta() {
    }

	
    public Bicicleta(int idBicicleta, EstadoBicicleta estadoBicicleta, Marca marca, TipoBicicleta tipoBicicleta) {
        this.idBicicleta = idBicicleta;
        this.estadoBicicleta = estadoBicicleta;
        this.marca = marca;
        this.tipoBicicleta = tipoBicicleta;
    }
    public Bicicleta(int idBicicleta, EstadoBicicleta estadoBicicleta, Marca marca, TipoBicicleta tipoBicicleta, String modelo, Integer precio, Date fechaRegistro, Byte estadoSincr, Set reservaBicicletas, Set mantencioneses) {
       this.idBicicleta = idBicicleta;
       this.estadoBicicleta = estadoBicicleta;
       this.marca = marca;
       this.tipoBicicleta = tipoBicicleta;
       this.modelo = modelo;
       this.precio = precio;
       this.fechaRegistro = fechaRegistro;
       this.estadoSincr = estadoSincr;
       this.reservaBicicletas = reservaBicicletas;
       this.mantencioneses = mantencioneses;
    }
   
    public int getIdBicicleta() {
        return this.idBicicleta;
    }
    
    public void setIdBicicleta(int idBicicleta) {
        this.idBicicleta = idBicicleta;
    }
    public EstadoBicicleta getEstadoBicicleta() {
        return this.estadoBicicleta;
    }
    
    public void setEstadoBicicleta(EstadoBicicleta estadoBicicleta) {
        this.estadoBicicleta = estadoBicicleta;
    }
    public Marca getMarca() {
        return this.marca;
    }
    
    public void setMarca(Marca marca) {
        this.marca = marca;
    }
    public TipoBicicleta getTipoBicicleta() {
        return this.tipoBicicleta;
    }
    
    public void setTipoBicicleta(TipoBicicleta tipoBicicleta) {
        this.tipoBicicleta = tipoBicicleta;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }
    public Integer getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Integer precio) {
        this.precio = precio;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Byte getEstadoSincr() {
        return this.estadoSincr;
    }
    
    public void setEstadoSincr(Byte estadoSincr) {
        this.estadoSincr = estadoSincr;
    }
    public Set getReservaBicicletas() {
        return this.reservaBicicletas;
    }
    
    public void setReservaBicicletas(Set reservaBicicletas) {
        this.reservaBicicletas = reservaBicicletas;
    }
    public Set getMantencioneses() {
        return this.mantencioneses;
    }
    
    public void setMantencioneses(Set mantencioneses) {
        this.mantencioneses = mantencioneses;
    }

    public boolean isSelectedAux() {
        return selectedAux;
    }

    public void setSelectedAux(boolean selectedAux) {
        this.selectedAux = selectedAux;
    }

    

    public String obtenerPrecioConFormato()
    {
        return Utilidades.formatearNumero((long)this.precio);
    }


}


