package com.arriendo.modelos;
// Generated 18-11-2017 19:47:29 by Hibernate Tools 4.3.1


import com.arriendo.utilidades.Utilidades;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private int rutCliente;
     private char dv;
     private String nombres;
     private String apellidos;
     private String email;
     private String telefono;
     private String direccion;
     private Date fechaNacimiento;
     private Date fechaRegistro;
     private String nacionalidad;
     private Byte estadoSincr;
     private Set reservas = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(int rutCliente, char dv, String nombres, String apellidos, String email, String telefono, String direccion, Date fechaNacimiento, Date fechaRegistro, String nacionalidad) {
        this.rutCliente = rutCliente;
        this.dv = dv;
        this.nombres = nombres;
        this.apellidos = apellidos;
        this.email = email;
        this.telefono = telefono;
        this.direccion = direccion;
        this.fechaNacimiento = fechaNacimiento;
        this.fechaRegistro = fechaRegistro;
        this.nacionalidad = nacionalidad;
    }
    public Cliente(int rutCliente, char dv, String nombres, String apellidos, String email, String telefono, String direccion, Date fechaNacimiento, Date fechaRegistro, String nacionalidad, Byte estadoSincr, Set reservas) {
       this.rutCliente = rutCliente;
       this.dv = dv;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.email = email;
       this.telefono = telefono;
       this.direccion = direccion;
       this.fechaNacimiento = fechaNacimiento;
       this.fechaRegistro = fechaRegistro;
       this.nacionalidad = nacionalidad;
       this.estadoSincr = estadoSincr;
       this.reservas = reservas;
    }
   
    public int getRutCliente() {
        return this.rutCliente;
    }
    
    public void setRutCliente(int rutCliente) {
        this.rutCliente = rutCliente;
    }
    public char getDv() {
        return this.dv;
    }
    
    public void setDv(char dv) {
        this.dv = dv;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public String getNacionalidad() {
        return this.nacionalidad;
    }
    
    public void setNacionalidad(String nacionalidad) {
        this.nacionalidad = nacionalidad;
    }
    public Byte getEstadoSincr() {
        return this.estadoSincr;
    }
    
    public void setEstadoSincr(Byte estadoSincr) {
        this.estadoSincr = estadoSincr;
    }
    public Set getReservas() {
        return this.reservas;
    }
    
    public void setReservas(Set reservas) {
        this.reservas = reservas;
    }

    public String rutConFormato()
    {
        return Utilidades.formatearNumero((long)this.rutCliente);
    }



}


