package com.arriendo.modelos;
// Generated 20-11-2017 14:02:58 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Garantia generated by hbm2java
 */
public class Garantia  implements java.io.Serializable {


     private int idGarantia;
     private Reserva reserva;
     private TipoGarantia tipoGarantia;
     private int montoGarantia;
     private Date fechaIngreso;
     private Integer montoDevuelto;
     private Date fechaDevolucion;
     private Set vouchers = new HashSet(0);

    public Garantia() {
    }

	
    public Garantia(int idGarantia, Reserva reserva, TipoGarantia tipoGarantia, int montoGarantia, Date fechaIngreso) {
        this.idGarantia = idGarantia;
        this.reserva = reserva;
        this.tipoGarantia = tipoGarantia;
        this.montoGarantia = montoGarantia;
        this.fechaIngreso = fechaIngreso;
    }
    public Garantia(int idGarantia, Reserva reserva, TipoGarantia tipoGarantia, int montoGarantia, Date fechaIngreso, Integer montoDevuelto, Date fechaDevolucion, Set vouchers) {
       this.idGarantia = idGarantia;
       this.reserva = reserva;
       this.tipoGarantia = tipoGarantia;
       this.montoGarantia = montoGarantia;
       this.fechaIngreso = fechaIngreso;
       this.montoDevuelto = montoDevuelto;
       this.fechaDevolucion = fechaDevolucion;
       this.vouchers = vouchers;
    }
   
    public int getIdGarantia() {
        return this.idGarantia;
    }
    
    public void setIdGarantia(int idGarantia) {
        this.idGarantia = idGarantia;
    }
    public Reserva getReserva() {
        return this.reserva;
    }
    
    public void setReserva(Reserva reserva) {
        this.reserva = reserva;
    }
    public TipoGarantia getTipoGarantia() {
        return this.tipoGarantia;
    }
    
    public void setTipoGarantia(TipoGarantia tipoGarantia) {
        this.tipoGarantia = tipoGarantia;
    }
    public int getMontoGarantia() {
        return this.montoGarantia;
    }
    
    public void setMontoGarantia(int montoGarantia) {
        this.montoGarantia = montoGarantia;
    }
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }
    public Integer getMontoDevuelto() {
        return this.montoDevuelto;
    }
    
    public void setMontoDevuelto(Integer montoDevuelto) {
        this.montoDevuelto = montoDevuelto;
    }
    public Date getFechaDevolucion() {
        return this.fechaDevolucion;
    }
    
    public void setFechaDevolucion(Date fechaDevolucion) {
        this.fechaDevolucion = fechaDevolucion;
    }
    public Set getVouchers() {
        return this.vouchers;
    }
    
    public void setVouchers(Set vouchers) {
        this.vouchers = vouchers;
    }




}


