package com.arriendo.modelos;
// Generated 20-11-2017 14:02:58 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Mantenciones generated by hbm2java
 */
public class Mantenciones  implements java.io.Serializable {


     private int idMantencion;
     private Bicicleta bicicleta;
     private Date fechaDesde;
     private Date fechaHasta;
     private String comentario;
     private Integer monto;

    public Mantenciones() {
    }

	
    public Mantenciones(int idMantencion, Bicicleta bicicleta, Date fechaDesde) {
        this.idMantencion = idMantencion;
        this.bicicleta = bicicleta;
        this.fechaDesde = fechaDesde;
    }
    public Mantenciones(int idMantencion, Bicicleta bicicleta, Date fechaDesde, Date fechaHasta, String comentario, Integer monto) {
       this.idMantencion = idMantencion;
       this.bicicleta = bicicleta;
       this.fechaDesde = fechaDesde;
       this.fechaHasta = fechaHasta;
       this.comentario = comentario;
       this.monto = monto;
    }
   
    public int getIdMantencion() {
        return this.idMantencion;
    }
    
    public void setIdMantencion(int idMantencion) {
        this.idMantencion = idMantencion;
    }
    public Bicicleta getBicicleta() {
        return this.bicicleta;
    }
    
    public void setBicicleta(Bicicleta bicicleta) {
        this.bicicleta = bicicleta;
    }
    public Date getFechaDesde() {
        return this.fechaDesde;
    }
    
    public void setFechaDesde(Date fechaDesde) {
        this.fechaDesde = fechaDesde;
    }
    public Date getFechaHasta() {
        return this.fechaHasta;
    }
    
    public void setFechaHasta(Date fechaHasta) {
        this.fechaHasta = fechaHasta;
    }
    public String getComentario() {
        return this.comentario;
    }
    
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }
    public Integer getMonto() {
        return this.monto;
    }
    
    public void setMonto(Integer monto) {
        this.monto = monto;
    }




}


