package com.arriendo.modelos;
// Generated 20-11-2017 14:02:58 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Multas generated by hbm2java
 */
public class Multas  implements java.io.Serializable {


     private int idMulta;
     private Reserva reserva;
     private Date fechaRegistro;
     private String descripcion;
     private int monto;
     private Date fechaPagoCliente;

    public Multas() {
    }

	
    public Multas(int idMulta, Reserva reserva, Date fechaRegistro, String descripcion, int monto) {
        this.idMulta = idMulta;
        this.reserva = reserva;
        this.fechaRegistro = fechaRegistro;
        this.descripcion = descripcion;
        this.monto = monto;
    }
    public Multas(int idMulta, Reserva reserva, Date fechaRegistro, String descripcion, int monto, Date fechaPagoCliente) {
       this.idMulta = idMulta;
       this.reserva = reserva;
       this.fechaRegistro = fechaRegistro;
       this.descripcion = descripcion;
       this.monto = monto;
       this.fechaPagoCliente = fechaPagoCliente;
    }
   
    public int getIdMulta() {
        return this.idMulta;
    }
    
    public void setIdMulta(int idMulta) {
        this.idMulta = idMulta;
    }
    public Reserva getReserva() {
        return this.reserva;
    }
    
    public void setReserva(Reserva reserva) {
        this.reserva = reserva;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public int getMonto() {
        return this.monto;
    }
    
    public void setMonto(int monto) {
        this.monto = monto;
    }
    public Date getFechaPagoCliente() {
        return this.fechaPagoCliente;
    }
    
    public void setFechaPagoCliente(Date fechaPagoCliente) {
        this.fechaPagoCliente = fechaPagoCliente;
    }




}


