package com.arriendo.modelos;
// Generated 20-11-2017 14:02:58 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Reserva generated by hbm2java
 */
public class Reserva  implements java.io.Serializable {


     private int idReserva;
     private Arriendo arriendo;
     private Cliente cliente;
     private Usuario usuario;
     private Date fechaSolicitud;
     private Date fechaRetiro;
     private int idSucursalRetiro;
     private Date fechaDevolucion;
     private int idSucursalDevolucion;
     private Date fechaRegistro;
     private Byte estadoSincr;
     private Set detalleReservas = new HashSet(0);
     private Set reservaAccesorioses = new HashSet(0);
     private Set multases = new HashSet(0);
     private Set reservaBicicletas = new HashSet(0);
     private Set daños = new HashSet(0);
     private Set seguros = new HashSet(0);
     private Set garantias = new HashSet(0);

    public Reserva() {
    }

	
    public Reserva(int idReserva, Cliente cliente, Usuario usuario, Date fechaSolicitud, Date fechaRetiro, int idSucursalRetiro, Date fechaDevolucion, int idSucursalDevolucion) {
        this.idReserva = idReserva;
        this.cliente = cliente;
        this.usuario = usuario;
        this.fechaSolicitud = fechaSolicitud;
        this.fechaRetiro = fechaRetiro;
        this.idSucursalRetiro = idSucursalRetiro;
        this.fechaDevolucion = fechaDevolucion;
        this.idSucursalDevolucion = idSucursalDevolucion;
    }
    public Reserva(int idReserva, Arriendo arriendo, Cliente cliente, Usuario usuario, Date fechaSolicitud, Date fechaRetiro, int idSucursalRetiro, Date fechaDevolucion, int idSucursalDevolucion, Date fechaRegistro, Byte estadoSincr, Set detalleReservas, Set reservaAccesorioses, Set multases, Set reservaBicicletas, Set daños, Set seguros, Set garantias) {
       this.idReserva = idReserva;
       this.arriendo = arriendo;
       this.cliente = cliente;
       this.usuario = usuario;
       this.fechaSolicitud = fechaSolicitud;
       this.fechaRetiro = fechaRetiro;
       this.idSucursalRetiro = idSucursalRetiro;
       this.fechaDevolucion = fechaDevolucion;
       this.idSucursalDevolucion = idSucursalDevolucion;
       this.fechaRegistro = fechaRegistro;
       this.estadoSincr = estadoSincr;
       this.detalleReservas = detalleReservas;
       this.reservaAccesorioses = reservaAccesorioses;
       this.multases = multases;
       this.reservaBicicletas = reservaBicicletas;
       this.daños = daños;
       this.seguros = seguros;
       this.garantias = garantias;
    }
   
    public int getIdReserva() {
        return this.idReserva;
    }
    
    public void setIdReserva(int idReserva) {
        this.idReserva = idReserva;
    }
    public Arriendo getArriendo() {
        return this.arriendo;
    }
    
    public void setArriendo(Arriendo arriendo) {
        this.arriendo = arriendo;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getFechaSolicitud() {
        return this.fechaSolicitud;
    }
    
    public void setFechaSolicitud(Date fechaSolicitud) {
        this.fechaSolicitud = fechaSolicitud;
    }
    public Date getFechaRetiro() {
        return this.fechaRetiro;
    }
    
    public void setFechaRetiro(Date fechaRetiro) {
        this.fechaRetiro = fechaRetiro;
    }
    public int getIdSucursalRetiro() {
        return this.idSucursalRetiro;
    }
    
    public void setIdSucursalRetiro(int idSucursalRetiro) {
        this.idSucursalRetiro = idSucursalRetiro;
    }
    public Date getFechaDevolucion() {
        return this.fechaDevolucion;
    }
    
    public void setFechaDevolucion(Date fechaDevolucion) {
        this.fechaDevolucion = fechaDevolucion;
    }
    public int getIdSucursalDevolucion() {
        return this.idSucursalDevolucion;
    }
    
    public void setIdSucursalDevolucion(int idSucursalDevolucion) {
        this.idSucursalDevolucion = idSucursalDevolucion;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Byte getEstadoSincr() {
        return this.estadoSincr;
    }
    
    public void setEstadoSincr(Byte estadoSincr) {
        this.estadoSincr = estadoSincr;
    }
    public Set getDetalleReservas() {
        return this.detalleReservas;
    }
    
    public void setDetalleReservas(Set detalleReservas) {
        this.detalleReservas = detalleReservas;
    }
    public Set getReservaAccesorioses() {
        return this.reservaAccesorioses;
    }
    
    public void setReservaAccesorioses(Set reservaAccesorioses) {
        this.reservaAccesorioses = reservaAccesorioses;
    }
    public Set getMultases() {
        return this.multases;
    }
    
    public void setMultases(Set multases) {
        this.multases = multases;
    }
    public Set getReservaBicicletas() {
        return this.reservaBicicletas;
    }
    
    public void setReservaBicicletas(Set reservaBicicletas) {
        this.reservaBicicletas = reservaBicicletas;
    }
    public Set getDaños() {
        return this.daños;
    }
    
    public void setDaños(Set datos) {
        this.daños = datos;
    }
    public Set getSeguros() {
        return this.seguros;
    }
    
    public void setSeguros(Set seguros) {
        this.seguros = seguros;
    }
    public Set getGarantias() {
        return this.garantias;
    }
    
    public void setGarantias(Set garantias) {
        this.garantias = garantias;
    }




}


