package com.arriendo.modelos;
// Generated 20-11-2017 14:02:58 by Hibernate Tools 4.3.1



/**
 * ReservaAccesorios generated by hbm2java
 */
public class ReservaAccesorios  implements java.io.Serializable {


     private ReservaAccesoriosId id;
     private Accesorio accesorio;
     private Reserva reserva;
     private int cantidad;
     private int monto;

    public ReservaAccesorios() {
    }

    public ReservaAccesorios(ReservaAccesoriosId id, Accesorio accesorio, Reserva reserva, int cantidad, int monto) {
       this.id = id;
       this.accesorio = accesorio;
       this.reserva = reserva;
       this.cantidad = cantidad;
       this.monto = monto;
    }
   
    public ReservaAccesoriosId getId() {
        return this.id;
    }
    
    public void setId(ReservaAccesoriosId id) {
        this.id = id;
    }
    public Accesorio getAccesorio() {
        return this.accesorio;
    }
    
    public void setAccesorio(Accesorio accesorio) {
        this.accesorio = accesorio;
    }
    public Reserva getReserva() {
        return this.reserva;
    }
    
    public void setReserva(Reserva reserva) {
        this.reserva = reserva;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public int getMonto() {
        return this.monto;
    }
    
    public void setMonto(int monto) {
        this.monto = monto;
    }




}


