package com.arriendo.modelos;
// Generated 18-11-2017 19:47:29 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Reserva generated by hbm2java
 */
public class Reserva  implements java.io.Serializable {


     private int idReserva;
     private Arriendo arriendo;
     private Cliente cliente;
     private Usuario usuario;
     private Date fechaSolicitud;
     private Date fechaRetiro;
     private int idSucursalRetiro;
     private Date fechaDevolucion;
     private int idSucursalDevolucion;
     private Date fechaRegistro;
     private Byte estadoSincr;

    public Reserva() {
    }

	
    public Reserva(int idReserva, Cliente cliente, Usuario usuario, Date fechaSolicitud, Date fechaRetiro, int idSucursalRetiro, Date fechaDevolucion, int idSucursalDevolucion) {
        this.idReserva = idReserva;
        this.cliente = cliente;
        this.usuario = usuario;
        this.fechaSolicitud = fechaSolicitud;
        this.fechaRetiro = fechaRetiro;
        this.idSucursalRetiro = idSucursalRetiro;
        this.fechaDevolucion = fechaDevolucion;
        this.idSucursalDevolucion = idSucursalDevolucion;
    }
    public Reserva(int idReserva, Arriendo arriendo, Cliente cliente, Usuario usuario, Date fechaSolicitud, Date fechaRetiro, int idSucursalRetiro, Date fechaDevolucion, int idSucursalDevolucion, Date fechaRegistro, Byte estadoSincr) {
       this.idReserva = idReserva;
       this.arriendo = arriendo;
       this.cliente = cliente;
       this.usuario = usuario;
       this.fechaSolicitud = fechaSolicitud;
       this.fechaRetiro = fechaRetiro;
       this.idSucursalRetiro = idSucursalRetiro;
       this.fechaDevolucion = fechaDevolucion;
       this.idSucursalDevolucion = idSucursalDevolucion;
       this.fechaRegistro = fechaRegistro;
       this.estadoSincr = estadoSincr;
    }
   
    public int getIdReserva() {
        return this.idReserva;
    }
    
    public void setIdReserva(int idReserva) {
        this.idReserva = idReserva;
    }
    public Arriendo getArriendo() {
        return this.arriendo;
    }
    
    public void setArriendo(Arriendo arriendo) {
        this.arriendo = arriendo;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getFechaSolicitud() {
        return this.fechaSolicitud;
    }
    
    public void setFechaSolicitud(Date fechaSolicitud) {
        this.fechaSolicitud = fechaSolicitud;
    }
    public Date getFechaRetiro() {
        return this.fechaRetiro;
    }
    
    public void setFechaRetiro(Date fechaRetiro) {
        this.fechaRetiro = fechaRetiro;
    }
    public int getIdSucursalRetiro() {
        return this.idSucursalRetiro;
    }
    
    public void setIdSucursalRetiro(int idSucursalRetiro) {
        this.idSucursalRetiro = idSucursalRetiro;
    }
    public Date getFechaDevolucion() {
        return this.fechaDevolucion;
    }
    
    public void setFechaDevolucion(Date fechaDevolucion) {
        this.fechaDevolucion = fechaDevolucion;
    }
    public int getIdSucursalDevolucion() {
        return this.idSucursalDevolucion;
    }
    
    public void setIdSucursalDevolucion(int idSucursalDevolucion) {
        this.idSucursalDevolucion = idSucursalDevolucion;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Byte getEstadoSincr() {
        return this.estadoSincr;
    }
    
    public void setEstadoSincr(Byte estadoSincr) {
        this.estadoSincr = estadoSincr;
    }




}


