package com.arriendo.modelos;
// Generated 20-11-2017 14:02:58 by Hibernate Tools 4.3.1



/**
 * ReservaBicicletaId generated by hbm2java
 */
public class ReservaBicicletaId  implements java.io.Serializable {


     private int idReserva;
     private int idBicicleta;

    public ReservaBicicletaId() {
    }

    public ReservaBicicletaId(int idReserva, int idBicicleta) {
       this.idReserva = idReserva;
       this.idBicicleta = idBicicleta;
    }
   
    public int getIdReserva() {
        return this.idReserva;
    }
    
    public void setIdReserva(int idReserva) {
        this.idReserva = idReserva;
    }
    public int getIdBicicleta() {
        return this.idBicicleta;
    }
    
    public void setIdBicicleta(int idBicicleta) {
        this.idBicicleta = idBicicleta;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ReservaBicicletaId) ) return false;
		 ReservaBicicletaId castOther = ( ReservaBicicletaId ) other; 
         
		 return (this.getIdReserva()==castOther.getIdReserva())
 && (this.getIdBicicleta()==castOther.getIdBicicleta());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdReserva();
         result = 37 * result + this.getIdBicicleta();
         return result;
   }   


}


