package com.arriendo.modelos;
// Generated 20-11-2017 14:02:58 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Seguro generated by hbm2java
 */
public class Seguro  implements java.io.Serializable {


     private int idSeguro;
     private String descripcion;
     private int monto;
     private Date desde;
     private Date hasta;
     private Set reservas = new HashSet(0);

    public Seguro() {
    }

	
    public Seguro(int idSeguro, String descripcion, int monto) {
        this.idSeguro = idSeguro;
        this.descripcion = descripcion;
        this.monto = monto;
    }
    public Seguro(int idSeguro, String descripcion, int monto, Date desde, Date hasta, Set reservas) {
       this.idSeguro = idSeguro;
       this.descripcion = descripcion;
       this.monto = monto;
       this.desde = desde;
       this.hasta = hasta;
       this.reservas = reservas;
    }
   
    public int getIdSeguro() {
        return this.idSeguro;
    }
    
    public void setIdSeguro(int idSeguro) {
        this.idSeguro = idSeguro;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public int getMonto() {
        return this.monto;
    }
    
    public void setMonto(int monto) {
        this.monto = monto;
    }
    public Date getDesde() {
        return this.desde;
    }
    
    public void setDesde(Date desde) {
        this.desde = desde;
    }
    public Date getHasta() {
        return this.hasta;
    }
    
    public void setHasta(Date hasta) {
        this.hasta = hasta;
    }
    public Set getReservas() {
        return this.reservas;
    }
    
    public void setReservas(Set reservas) {
        this.reservas = reservas;
    }




}


