package com.arriendo.modelos;
// Generated 20-11-2017 14:02:58 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Sucursal generated by hbm2java
 */
public class Sucursal  implements java.io.Serializable {


     private int idSucursal;
     private String descripcionSucursal;
     private Set stocksucursals = new HashSet(0);
     private Set detalleReservas = new HashSet(0);

    public Sucursal() {
    }

	
    public Sucursal(int idSucursal, String descripcionSucursal) {
        this.idSucursal = idSucursal;
        this.descripcionSucursal = descripcionSucursal;
    }
    public Sucursal(int idSucursal, String descripcionSucursal, Set stocksucursals, Set detalleReservas) {
       this.idSucursal = idSucursal;
       this.descripcionSucursal = descripcionSucursal;
       this.stocksucursals = stocksucursals;
       this.detalleReservas = detalleReservas;
    }
   
    public int getIdSucursal() {
        return this.idSucursal;
    }
    
    public void setIdSucursal(int idSucursal) {
        this.idSucursal = idSucursal;
    }
    public String getDescripcionSucursal() {
        return this.descripcionSucursal;
    }
    
    public void setDescripcionSucursal(String descripcionSucursal) {
        this.descripcionSucursal = descripcionSucursal;
    }
    public Set getStocksucursals() {
        return this.stocksucursals;
    }
    
    public void setStocksucursals(Set stocksucursals) {
        this.stocksucursals = stocksucursals;
    }
    public Set getDetalleReservas() {
        return this.detalleReservas;
    }
    
    public void setDetalleReservas(Set detalleReservas) {
        this.detalleReservas = detalleReservas;
    }




}


