package com.arriendo.modelos;
// Generated 18-11-2017 19:47:29 by Hibernate Tools 4.3.1



/**
 * Sucursal generated by hbm2java
 */
public class Sucursal  implements java.io.Serializable {


     private int idSucursal;
     private String descripcionSucursal;

    public Sucursal() {
    }

    public Sucursal(int idSucursal, String descripcionSucursal) {
       this.idSucursal = idSucursal;
       this.descripcionSucursal = descripcionSucursal;
    }
   
    public int getIdSucursal() {
        return this.idSucursal;
    }
    
    public void setIdSucursal(int idSucursal) {
        this.idSucursal = idSucursal;
    }
    public String getDescripcionSucursal() {
        return this.descripcionSucursal;
    }
    
    public void setDescripcionSucursal(String descripcionSucursal) {
        this.descripcionSucursal = descripcionSucursal;
    }




}


