package com.arriendo.modelos;
// Generated 20-11-2017 14:02:58 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoGarantia generated by hbm2java
 */
public class TipoGarantia  implements java.io.Serializable {


     private int idTipoGarantia;
     private String descripcion;
     private Set garantias = new HashSet(0);

    public TipoGarantia() {
    }

	
    public TipoGarantia(int idTipoGarantia, String descripcion) {
        this.idTipoGarantia = idTipoGarantia;
        this.descripcion = descripcion;
    }
    public TipoGarantia(int idTipoGarantia, String descripcion, Set garantias) {
       this.idTipoGarantia = idTipoGarantia;
       this.descripcion = descripcion;
       this.garantias = garantias;
    }
   
    public int getIdTipoGarantia() {
        return this.idTipoGarantia;
    }
    
    public void setIdTipoGarantia(int idTipoGarantia) {
        this.idTipoGarantia = idTipoGarantia;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getGarantias() {
        return this.garantias;
    }
    
    public void setGarantias(Set garantias) {
        this.garantias = garantias;
    }




}


