package com.arriendo.modelos;
// Generated 20-11-2017 14:02:58 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoDetalleReserva generated by hbm2java
 */
public class TipoDetalleReserva  implements java.io.Serializable {


     private int idTipoDetalle;
     private String descripcion;
     private Set detalleReservas = new HashSet(0);

    public TipoDetalleReserva() {
    }

	
    public TipoDetalleReserva(int idTipoDetalle, String descripcion) {
        this.idTipoDetalle = idTipoDetalle;
        this.descripcion = descripcion;
    }
    public TipoDetalleReserva(int idTipoDetalle, String descripcion, Set detalleReservas) {
       this.idTipoDetalle = idTipoDetalle;
       this.descripcion = descripcion;
       this.detalleReservas = detalleReservas;
    }
   
    public int getIdTipoDetalle() {
        return this.idTipoDetalle;
    }
    
    public void setIdTipoDetalle(int idTipoDetalle) {
        this.idTipoDetalle = idTipoDetalle;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getDetalleReservas() {
        return this.detalleReservas;
    }
    
    public void setDetalleReservas(Set detalleReservas) {
        this.detalleReservas = detalleReservas;
    }




}


