package com.arriendo.modelos;
// Generated 20-11-2017 14:02:58 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int idUsuario;
     private Rol rol;
     private String login;
     private String password;
     private String nombres;
     private String apellidos;
     private Date fechaNacimiento;
     private String email;
     private String telefono;
     private Byte bloqueado;
     private Set reservas = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(int idUsuario, Rol rol, String login, String password, String nombres, String apellidos, String email, String telefono) {
        this.idUsuario = idUsuario;
        this.rol = rol;
        this.login = login;
        this.password = password;
        this.nombres = nombres;
        this.apellidos = apellidos;
        this.email = email;
        this.telefono = telefono;
    }
    public Usuario(int idUsuario, Rol rol, String login, String password, String nombres, String apellidos, Date fechaNacimiento, String email, String telefono, Byte bloqueado, Set reservas) {
       this.idUsuario = idUsuario;
       this.rol = rol;
       this.login = login;
       this.password = password;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.fechaNacimiento = fechaNacimiento;
       this.email = email;
       this.telefono = telefono;
       this.bloqueado = bloqueado;
       this.reservas = reservas;
    }
   
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public Byte getBloqueado() {
        return this.bloqueado;
    }
    
    public void setBloqueado(Byte bloqueado) {
        this.bloqueado = bloqueado;
    }
    public Set getReservas() {
        return this.reservas;
    }
    
    public void setReservas(Set reservas) {
        this.reservas = reservas;
    }




}


