package com.arriendo.modelos;
// Generated 20-11-2017 14:02:58 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Voucher generated by hbm2java
 */
public class Voucher  implements java.io.Serializable {


     private int idVoucher;
     private int codigo;
     private int monto;
     private String archivoFisico;
     private String fechaRegistro;
     private Set garantias = new HashSet(0);

    public Voucher() {
    }

	
    public Voucher(int idVoucher, int codigo, int monto) {
        this.idVoucher = idVoucher;
        this.codigo = codigo;
        this.monto = monto;
    }
    public Voucher(int idVoucher, int codigo, int monto, String archivoFisico, String fechaRegistro, Set garantias) {
       this.idVoucher = idVoucher;
       this.codigo = codigo;
       this.monto = monto;
       this.archivoFisico = archivoFisico;
       this.fechaRegistro = fechaRegistro;
       this.garantias = garantias;
    }
   
    public int getIdVoucher() {
        return this.idVoucher;
    }
    
    public void setIdVoucher(int idVoucher) {
        this.idVoucher = idVoucher;
    }
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public int getMonto() {
        return this.monto;
    }
    
    public void setMonto(int monto) {
        this.monto = monto;
    }
    public String getArchivoFisico() {
        return this.archivoFisico;
    }
    
    public void setArchivoFisico(String archivoFisico) {
        this.archivoFisico = archivoFisico;
    }
    public String getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(String fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Set getGarantias() {
        return this.garantias;
    }
    
    public void setGarantias(Set garantias) {
        this.garantias = garantias;
    }




}


